services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  fill_db:
    container_name: fill_db
    build:
      context: ./fill_db
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./fill_db:/app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/db
    depends_on:
      mongo-gridfs:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./fastapi:/app

  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-gridfs:
    image: mongo:7.0
    container_name: mongo-gridfs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./GridFS/books:/books
      - ./GridFS/init_gridfs.sh:/docker-entrypoint-initdb.d/init_gridfs.sh
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  tunnel:
    image: node:alpine
    container_name: tunnel
    command: >
      sh -c "
      npm install -g localtunnel &&
      lt --port 8080 --subdomain fast-api-maxminiapp"
    network_mode: host
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
