services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  
  student_backend:
    container_name: student_backend
    build:
      context: student/spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      CORS_ALLOWED_ORIGINS: https://vsuetstudent.cloudpub.ru
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  student_frontend:
    container_name: student_frontend
    build:
      context: student/front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://studentback.cloudpub.ru/api
      - NEXT_PUBLIC_WS_URL=ws://studentback.cloudpub.ru/ws
      - NEXT_PUBLIC_SOCKET_URL=https://studentback.cloudpub.ru/ws
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


volumes:
  postgres_data: