
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      # Папка для SQL-скриптов инициализации (init.sql, fill_users.sql)
      - ./db/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 1. Загрузка групп и студентов (student_info должен заполнять и groups)
  student_info:
    container_name: student_info
    build:
      context: ./parsers/student_info
      dockerfile: Dockerfile
    shm_size: '2gb'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db

  # 2. Загрузка расписания студентов (Зависит только от DB, но логически от student_info/groups)
  student_timetable:
    container_name: student_timetable
    build:
      context: ./parsers/students_timetable
      dockerfile: Dockerfile
    shm_size: '2gb'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db

  # 3. Загрузка расписания преподавателей
  teacher_timetable:
    container_name: teacher_timetable
    build:
      context: ./parsers/teachers_timetable
      dockerfile: Dockerfile
    shm_size: '2gb'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db

  # 4. Загрузка информации о преподавателях (Зависит от teacher_timetable)
  teacher_info:
    container_name: teacher_info
    build:
      context: ./parsers/teacher_info
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      teacher_timetable:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db

  # 5. ПАРСЕР ПОСЕЩАЕМОСТИ (attendance.py) - Запускается ПОСЛЕ ВСЕХ ОСНОВНЫХ ДАННЫХ
  attendance_parser:
    container_name: attendance
    build:
      context: ./parsers/attendance
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      student_timetable: # Нужны ID групп и расписание студентов
        condition: service_completed_successfully
      student_info: # Нужны ID групп и студенты
        condition: service_completed_successfully
      teacher_info: # НУЖНЫ ID ПРЕПОДАВАТЕЛЕЙ (ИСПРАВЛЕНО)
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db
  

volumes:
  postgres_data: