services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    container_name: radis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  full_timetable:
    container_name: full_timetable
    build: 
      context: ./parsers/full_timetable
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db
    
  teachers_info:
    container_name: teachers_info
    build:
      context: ./parsers/teacher_info
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      full_timetable:
        condition: service_completed_successfully

  students_info:
    container_name: students_info
    build:
      context: ./parsers/students_info
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      full_timetable:
        condition: service_completed_successfully

volumes:
  postgres_data:
  redis_data: