apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:  # Используем stringData вместо data для удобства
  DB_HOST: "postgres"  
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "admin"
  DB_NAME: "db"