apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=          # admin
  POSTGRES_PASSWORD: YWRtaW4=      # admin
  POSTGRES_DB: ZGI=                # db