apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq"
spec:
  namespaceSelector: {}  # Разрешает все неймспейсы
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: default-flavor
          resources:
            - name: "cpu"
              nominalQuota: 2  
            - name: "memory"
              nominalQuota: 3Gi