services:
  db:
    image: buildo/h2database
    container_name: h2
    environment:
      - H2_OPTIONS=-ifNotExists -baseDir /opt/h2-data -init /docker-entrypoint-initdb.d/init.sql
    ports:
      - "9092:9092"  # TCP порт для JDBC
      - "8082:8082"  # Веб-консоль
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - h2-data:/opt/h2-data
    restart: unless-stopped


volumes:
  h2-data: